CREATE TABLE `contacts` (
	`id` serial AUTO_INCREMENT NOT NULL,
	`name` varchar(50) NOT NULL,
	`email` varchar(100) NOT NULL,
	`phone` varchar(100) NOT NULL DEFAULT '',
	`password` varchar(255) NOT NULL,
	`reset_token` varchar(255),
	`email_token` varchar(255),
	`created_at` timestamp DEFAULT (now()),
	`updated_at` timestamp DEFAULT (now()),
	`role` enum('lead','user') DEFAULT 'lead',
	`profile_picture` text,
	`bio` varchar(255),
	`custom_id` varchar(255),
	`is_verified` boolean DEFAULT false,
	`stripe_customer_id` varchar(255),
	`subscription_id` varchar(255),
	`subscription_status` enum('trialing','active','past_due','canceled','incomplete','incomplete_expired','paused','unpaid'),
	`google_id` varchar(255),
	`google_access_token` varchar(255),
	`auth_provider` enum('local','google') DEFAULT 'local',
	CONSTRAINT `contacts_id` PRIMARY KEY(`id`),
	CONSTRAINT `contacts_email_unique` UNIQUE(`email`)
);
